### ISSUE TITLE
Create pop-out chat?

### ISSUE THREAD

**Issue by companyhen** [gdpelican/babble#190]
Is it possible/easy to add pop-out window for the chat? Users asking for it. Thanks!

**Comment by gdpelican** [comment]
You'll have to be a little more descriptive than that; what means pop-out window? Like facebook does it?

Although... heh, it's probably not easy. Some sort of docking thing might be possible? But more than likely we'll revamp this more thoroughly in the next iteration.

**Comment by companyhen** [comment]
For example, plug.dj has a popout window chat. Like this:

**Comment by gdpelican** [comment]
I've now made it so that if you have full page chat enabled, you can go directly to the full page chat from the shoutbox by clicking on the icon to the top right:
![screen shot 2017-03-11 at 10 33 15 am](https://cloud.githubusercontent.com/assets/750477/23813979/5ab5d6a2-0646-11e7-91d3-eab7e4a22aa4.png)


Ctrl (or command) clicking that icon will open in a new tab or window (depending on your browser preferences)

**Comment by gdpelican** [comment]
Let me know how that lands for you, happy to do further tweaking to make it a nicer experience (although I'm somewhat limited because most browsers have default settings to disallow us throwing out pop-ups everywhere)
