### ISSUE TITLE
feature request: Add a new setting to customize the tooltip string. 

### ISSUE THREAD

**Issue by tedstrauss** [gdpelican/babble#76]
Add a new admin setting to customize the tooltip string. It currently displays "Shoutbox!" which is not very useful for users.

**Comment by gdpelican** [comment]
Turns out this is tricker than I'd like, because Discourse's menu directives are hard-coded to accept a translation string, which means customization will require going in and editing the client.en.yml file on your instance.

However, I've updated the messaging to be a little less worthless and a little more consistent with the menus in #82

**Comment by tedstrauss** [comment]
thanks, that's an improvement for sure.
and now i know how to edit the string if i need to.
