### ISSUE TITLE
feature request: filter babble topic from email digest

### ISSUE THREAD

**Issue by tedstrauss** [gdpelican/babble#77]
I am getting babble posts showing up in my email digest, which is weird. I see 2 possible ways of fixing this: i) force exclusion of the babble post from digest. ii) provide a setting (checkbox) that filters out all posts from designated babble category from the digest.

**Comment by gdpelican** [comment]
Hmm.. is there a way to exclude certain categories from the email digest? All the chat topics should be in the 'chat' category, so that might be a nice workaround.

**Comment by gdpelican** [comment]
Hey @tedstrauss : I think the fix for this is twofold:

- Go into your rails console, and update all of the users to have a 'muted' setting for the 'chat' category
Something like this:

```
category = Category.find_by(name: "chat")
CategoryUser.where(category: category).update_all(notification_level: CategoryUser.notification_levels[:muted])
```
(This will handle all users who have already written a chat message)

- Go into the `/admin/site_settings` panel and do a search for `default categories`. Apply 'chat' to the `default_categories_muted` field, like so:

![screen shot 2015-11-24 at 8 44 19 am](https://cloud.githubusercontent.com/assets/750477/11354594/9a011a76-9287-11e5-9ea4-de7d796e93a9.png)

(I may put in a PR so Babble does step 2 automatically, but this is a pretty simple workaround)

**Comment by tedstrauss** [comment]
Ok I'll try that method out.
But won't I have to do it periodically as new users register?
Thanks!

**Comment by gdpelican** [comment]
Running the first command will take care of all exising users, while
editing the site setting will take care of it for future users.
