### ISSUE TITLE
Display 'no messages yet' placeholder when topic is empty

### ISSUE THREAD

**Issue by gdpelican** [gdpelican/babble#9]
Currently, creating a topic starts the user out with just a composer, and no indication of what the heck this thing is.

I'd like to have some sort of placeholder message there to tell the user 'This chat channel is empty. Type in a message below to get started!'

**Comment by JSey** [comment]
Hm… we would have two++ options here:
a. create the default thread automatically, and place the welcome text there. This could even be static, since an active chat will scroll away this default posting soon.
b. have a "real" placeholder in the babble composer. This can even stay in place after the chat is active. Like so:
![bildschirmfoto 2015-08-07 um 08 05 55](https://cloud.githubusercontent.com/assets/9109505/9129705/741c9aa8-3cdb-11e5-917d-ce4eea5ed266.png)
c. create a "smart" placeholder which is only there if there are no chat messages. For the new user, option b. offers more guidance I think. 

Which would be the best in your opinion?

**Comment by gdpelican** [comment]
Yeah, a placeholder's probably the right call. I imagine the one you've got in that screenshot would do nicely. Care to PR it?

**Comment by JSey** [comment]
On it. Just wanted to make sure we're thinking about the same thing. Unfortunately, due to the {{textarea component, I need to take some detours to get the i18n stuff straight. But will send you a PR as soon as it's done (hopefully today, since I will be afk for some days starting tomorrow).

**Comment by gdpelican** [comment]
Closed with #19
