### ISSUE TITLE
Channel title restrictions

### ISSUE THREAD

**Issue by kymetro9999** [gdpelican/babble#94]
When creating a new channel, the Channel Title must meet all the requirements of a topic title - min length, min entropy, prettify, no duplicate topics, etc.

It would make sense to bypass the usual restrictions for a chat title. "Live Chat" for example is too short to meet the default 15 char minimum. 

If the title is not acceptable, the only error given is "Unable to save that chat channel. Please try again." This is too generic, it can indicate any number of problems with the plugin.

Either:
- bypass the usual title requirements
- show more descriptive errors
- have an error log somewhere

**Comment by gdpelican** [comment]
Thanks for the report; I agree that forcing a certain title length is less than ideal. There's always a complexity cost with doing something different than what Discourse does normally with all this stuff, but I'm open to putting it in if I can find an easy way to bypass validation.

More descriptive errors is definitely something that could go in. I'm not convinced these should go in the regular Discourse error log, since they are 422 (Unprocessable Entity), ie user error.
